exclude: '_site/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.285.3
    hooks:
      - id: renovate-config-validator
        args: [ --strict ]
  - repo: https://gitlab.cee.redhat.com/infosec-public/developer-workbench/tools.git
    rev: rh-pre-commit-2.3.2
    hooks:
      # If you have not run this hook on your system before, it may prompt you to
      # log in for patterns, and you will need to try again.
      #
      # Docs: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit
      - id: rh-pre-commit
      - id: rh-pre-commit.commit-msg # Optional for commit-msg attestation
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/vale-cli/vale
    rev: v3.17.0
    hooks:
      - id: vale
        name: vale sync
        pass_filenames: false
        args: [sync]
      - id: vale
        files: \.(md|markdown)$
        args: [--output=line, --minAlertLevel=error]
