name: build-test-site

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docs-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: |
          bundle install
      - name: Build and Test
        run: |
          bundle exec jekyll build
          bundle exec htmlproofer --disable-external=true ./_site
